server:
  port: 9002
spring:
  datasource:
    dirverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dep_service
    username: root
    password: 1234abcd
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true